spring.application.name=todos

spring.datasource.url=jdbc:mysql://localhost:3306/notesdb
spring.datasource.username=
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

server.servlet.context-path=/api

jwt.secretKey=ad564a9df84da7df1a96d4fas1d1f9a8sdf5as51df9as84df51sdf9as4df5as1d9f4asdf1as98df4s6a5d1f9as4df65sa1df94asdf51as9d8f46as8d4f9asd1f9as4f



